version: 2
jobs:
  build_win_32:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: setup for Windows 32
          command: |
            apt-get update && apt-get install -y mingw-w64
            bash config.sh
      - run:
          name: Build for Windows 32   
          command: bash build.sh
  build_win_64:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Build for Windows 64
          command: |
            apt-get update && apt-get install -y mingw-w64
            bash ci/build_win64.sh
workflows:
  version: 2
  build_all:
    jobs:
      - build_win_32
      - build_win_64
      
