version: 2
jobs:
  build_win_32:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: setup for Windows 32
          command: |
            apt-get update && apt-get install -y mingw-w64 curl
            bash config.sh
            ls -la
            bash check_folders.sh
            ls -la
      - run:
          name: Build for Windows 32   
          command: | 
            chmod +x ./build-zlib-1.2.8.sh
            bash build.sh
  build_win_64:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: Build for Windows 64
          command: |
            apt-get update && apt-get install -y mingw-w64
            bash ci/build_win64.sh
workflows:
  version: 2
  build_all:
    jobs:
      - build_win_32
      
